// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtQldTC0M14oPpvfwHzcO_zVptpS41pM4',
    appId: '1:280383455653:web:831e23101133837d3a284c',
    messagingSenderId: '280383455653',
    projectId: 'c4nteen-efa2a',
    authDomain: 'c4nteen-efa2a.firebaseapp.com',
    storageBucket: 'c4nteen-efa2a.firebasestorage.app',
    measurementId: 'G-KJ95EEFRER',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhV2yr_7Yonv1XKfylt-Mj_jFz9p9wPc4',
    appId: '1:280383455653:android:38ec0c623d9da3193a284c',
    messagingSenderId: '280383455653',
    projectId: 'c4nteen-efa2a',
    storageBucket: 'c4nteen-efa2a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtyq4dw7a9QOdj2sEMiTempKBZlRAVbeY',
    appId: '1:280383455653:ios:fcb6c2d07d5a58ae3a284c',
    messagingSenderId: '280383455653',
    projectId: 'c4nteen-efa2a',
    storageBucket: 'c4nteen-efa2a.firebasestorage.app',
    iosBundleId: 'com.C4NTEEN.c4nteen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtyq4dw7a9QOdj2sEMiTempKBZlRAVbeY',
    appId: '1:280383455653:ios:fcb6c2d07d5a58ae3a284c',
    messagingSenderId: '280383455653',
    projectId: 'c4nteen-efa2a',
    storageBucket: 'c4nteen-efa2a.firebasestorage.app',
    iosBundleId: 'com.C4NTEEN.c4nteen',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAtQldTC0M14oPpvfwHzcO_zVptpS41pM4',
    appId: '1:280383455653:web:4b79c7a05831abeb3a284c',
    messagingSenderId: '280383455653',
    projectId: 'c4nteen-efa2a',
    authDomain: 'c4nteen-efa2a.firebaseapp.com',
    storageBucket: 'c4nteen-efa2a.firebasestorage.app',
    measurementId: 'G-SGZ770QE4Y',
  );
}
